name: Build Android .so

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.22.4

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Android SDK and NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "ndk;25.2.9519653"
        echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Build .so for Android
      run: |
        mkdir -p build
        ARCHS=("arm" "arm64" "386" "amd64")
        for arch in "${ARCHS[@]}"; do
          echo "Building for $arch..."
          GOOS=android GOARCH=$arch go build -buildmode=c-shared -o build/libdnstt_$arch.so ./mobile
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dnstt-android-so
        path: build/*.so
